// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXdLehqUVkO7VzTCRR6zpugKFeQS4xaCk',
    appId: '1:579628714680:web:1492d361622b85c839424d',
    messagingSenderId: '579628714680',
    projectId: 'fir-692e9',
    authDomain: 'fir-692e9.firebaseapp.com',
    storageBucket: 'fir-692e9.firebasestorage.app',
    measurementId: 'G-EM8RFETPKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-t5B0uEwXICrOGGyLr3s5__7YG8pOSU',
    appId: '1:579628714680:android:99460d2e4faa0afe39424d',
    messagingSenderId: '579628714680',
    projectId: 'fir-692e9',
    storageBucket: 'fir-692e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIPr0eb9MIkpC0Azn3bdI8AO8VaW_ldNs',
    appId: '1:579628714680:ios:12efaa65646970bf39424d',
    messagingSenderId: '579628714680',
    projectId: 'fir-692e9',
    storageBucket: 'fir-692e9.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIPr0eb9MIkpC0Azn3bdI8AO8VaW_ldNs',
    appId: '1:579628714680:ios:12efaa65646970bf39424d',
    messagingSenderId: '579628714680',
    projectId: 'fir-692e9',
    storageBucket: 'fir-692e9.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXdLehqUVkO7VzTCRR6zpugKFeQS4xaCk',
    appId: '1:579628714680:web:020421c3b711790139424d',
    messagingSenderId: '579628714680',
    projectId: 'fir-692e9',
    authDomain: 'fir-692e9.firebaseapp.com',
    storageBucket: 'fir-692e9.firebasestorage.app',
    measurementId: 'G-6EW6CT0HV5',
  );
}
